### ISSUE TITLE
PDFDocument#output is deprecated, and has been removed from PDFKit

### ISSUE THREAD

**Issue by rbreaves** [williamkapke/ipp#69]
This is the current error that is received when running the example code. Did PDFKit update their package and break compatibility with this project?

`/Users/*/Documents/git-projects/ippTest/node_modules/pdfkit/js/document.js:183
      throw new Error('PDFDocument#output is deprecated, and has been removed from PDFKit. Please pipe the document into a Node stream.');
      ^

Error: PDFDocument#output is deprecated, and has been removed from PDFKit. Please pipe the document into a Node stream.
    at PDFDocument.output (/Users/ryanreaves/Documents/git-projects/ippTest/node_modules/pdfkit/js/document.js:183:13)
    at Object.<anonymous> (/Users/ryanreaves/Documents/git-projects/ippTest/test.js:8:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)`

**Comment by StefanScherer** [comment]
Thank you for the heads up.

**Comment by atiertant** [comment]
@rbreaves you could try [pclkit](https://github.com/Atlantis-Software/pclkit)
